filter:
    excluded_paths: [vendor/*]

tools:
    php_mess_detector: true
    php_cpd: true
    php_pdepend:
        excluded_dirs: [vendor]
    php_code_coverage: true

before_commands:
    - "composer install --prefer-source"
